# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarentry',
            options={'ordering': ('end', 'start'), 'verbose_name': 'calendar entry', 'verbose_name_plural': 'calendar entries'},
        ),
        migrations.AlterField(
            model_name='calendarentry',
            name='busy',
            field=models.BooleanField(default=False, help_text='Busy or available, defaults to available (False)'),
        ),
        migrations.AlterField(
            model_name='calendarentry',
            name='end',
            field=models.DateTimeField(help_text='End of the time period'),
        ),
        migrations.AlterField(
            model_name='calendarentry',
            name='start',
            field=models.DateTimeField(help_text='Start of the time period'),
        ),
    ]
