# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('addressType', models.CharField(choices=[('snailmail', 'Snail mail')], max_length=16)),
                ('streetAddress', models.CharField(max_length=255)),
                ('streetAddress2', models.CharField(blank=True, max_length=255)),
                ('streetAddress3', models.CharField(blank=True, max_length=255)),
                ('postbox', models.CharField(blank=True, max_length=255)),
                ('postalcode', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=255)),
                ('subregion', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('businessid', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Company'),
        ),
    ]
