# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='organisation.Company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='businessid',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
