# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_auto_20160419_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linktype', models.CharField(choices=[('web', 'Homepage'), ('youtube', 'Youtube'), ('facebook', 'Facebook'), ('other', 'Other')], max_length=32)),
                ('other_description', models.CharField(blank=True, help_text="Link description when type is 'other'", max_length=128)),
                ('url', models.URLField(max_length=512)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='organisation.Company')),
            ],
        ),
        migrations.AlterField(
            model_name='companydescription',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Company'),
        ),
    ]
