# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_company_service_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default='0', help_text='Hourly rate in EUR', max_digits=32),
            preserve_default=False,
        ),
    ]
