# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('organisation', '0006_company_price_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='offered_services',
            field=models.ManyToManyField(blank=True, to='services.ServicePackage'),
        ),
    ]
