# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0007_company_offered_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='price_per_hour_continuing',
            field=models.DecimalField(decimal_places=2, default='0', help_text='Hourly rate in EUR for continuing service', max_digits=32),
            preserve_default=False,
        ),
    ]
