# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 09:36
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisation', '0009_companydescription_service_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, help_text='Freeform message')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='A rating between 1 and 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('company', models.ForeignKey(help_text='The company who receives the rating', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='organisation.Company')),
                ('user', models.ForeignKey(blank=True, help_text='User who makes the rating. Optional', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
