# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('organisation', '0010_companyrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('num', models.IntegerField(default=0, help_text='Order number')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Company')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Image')),
            ],
            options={
                'ordering': ('num', 'id'),
            },
        ),
    ]
