# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0013_auto_20160525_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, help_text='Customer facing email address', max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, help_text='Customer facing phone number', max_length=128),
        ),
    ]
