# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 08:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0015_company_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate in EUR', max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='price_per_hour_continuing',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate in EUR for continuing service', max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='service_areas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), blank=True, help_text='Postal codes of the areas in which this company provides service', size=None),
        ),
    ]
