# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0016_auto_20160615_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='YTRCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', editable=False, max_length=20, null=True, verbose_name='YTR code')),
            ],
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='ytrcompany',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ytr', to='organisation.Company'),
        ),
    ]
