# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palvelutori', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='phone number'),
        ),
    ]
