# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palvelutori', '0003_auto_20160420_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('address_street', models.CharField(max_length=255)),
                ('address_street2', models.CharField(blank=True, max_length=255)),
                ('address_postalcode', models.CharField(max_length=32)),
                ('address_city', models.CharField(max_length=255)),
                ('address_country', models.CharField(default='FIN', editable=False, max_length=3)),
                ('room_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sanitary_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('floor_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('floor_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
