# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ('-created',), 'permissions': (('see_all', "Can see every user's log entries"),)},
        ),
    ]
