# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 10:03
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0012_auto_20160511_1550'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_first_name', models.CharField(max_length=30)),
                ('user_last_name', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=255)),
                ('user_phone', models.CharField(max_length=50)),
                ('site_address_street', models.CharField(max_length=255)),
                ('site_address_street2', models.CharField(blank=True, max_length=255)),
                ('site_address_postalcode', models.CharField(max_length=32)),
                ('site_address_city', models.CharField(max_length=255)),
                ('site_address_country', models.CharField(default='FIN', editable=False, max_length=3)),
                ('site_room_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('site_sanitary_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('site_floor_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('site_floor_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('service_package_shortname', models.SlugField()),
                ('duration', models.DecimalField(decimal_places=1, help_text='Duration of the service (decimal with one decimal place, max value 999.9)', max_digits=4)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the service (decimal with two decimal places, max value 99999.99)', max_digits=7)),
                ('timeslot_start', models.DateTimeField(help_text='Start of the time slot')),
                ('timeslot_end', models.DateTimeField(help_text='End of the time slot')),
                ('extra_info', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='A rating between 1 and 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Company')),
                ('service_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.ServicePackage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
