# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rated',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(help_text='company id', on_delete=django.db.models.deletion.CASCADE, to='organisation.Company'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_package',
            field=models.ForeignKey(blank=True, help_text='service package id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.ServicePackage'),
        ),
        migrations.AlterField(
            model_name='order',
            name='timeslot_end',
            field=models.DateTimeField(help_text='datetime in ISO 8601 format'),
        ),
        migrations.AlterField(
            model_name='order',
            name='timeslot_start',
            field=models.DateTimeField(help_text='datetime in ISO 8601 format'),
        ),
    ]
